### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#10]
We should add linter of some kind and rules to enforce a certain code style.

We can discuss this code style here.

The linter validation should be a prerequesite to the CI pipeline

**Comment by maximelouet** [comment]
Whoops, I already added a linter (ESLint) with Airbnb's config (the most used one). We can discuss this here of course :smile:

**Comment by AnastasiaPromtep** [comment]
Indeed it is already done.
For documentation purposes I leave this link here : https://github.com/airbnb/javascript
