### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#11]
We need to update the README.md file withe this basic information
- Description of this project
- How to set up
- License
- Author
- ...

**Comment by maximelouet** [comment]
Depends on #4, #5, #6, #7, #8.

**Comment by maximelouet** [comment]
As we have not yet decided on a license I created a dedicated issue which will allow us to edit the README later: https://github.com/lapoissonnerie/touiteur-api/issues/30
