### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by maximelouet** [lapoissonnerie/touiteur-api#30]
We need to https://choosealicense.com/ for this project. Once this is done we should provide a LICENSE file and update the README accordingly.

**Comment by maximelouet** [comment]
I think the Apache 2.0 license is fine for us : https://choosealicense.com/licenses/apache-2.0/

It's the license I use in all of my new projects because it's quite permissive but still provides explicit rules regarding credit and notices.

What do you think @AnastasiaPromtep ?

**Comment by AnastasiaPromtep** [comment]
Okay I will add this license to all Touiteur projects
