### ISSUE TITLE
Set up the CD

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#7]
We should add an automated deployment pipeline
This involves a production environment that we need to discuss.

**Comment by maximelouet** [comment]
We can host this shit on Grepimmo's VPS with Docker Swarm. This would cost us nothing. What do you think? Should we buy a domain name? I have `saumon.dev` so we can do `touiteur.saumon.dev` but I'm okay to buy another one if you don't want my name in the URL which I understand?

**Comment by AnastasiaPromtep** [comment]
I'm okay to reuse a something.
Keep in mind we will need an url for the front end as well

**Comment by maximelouet** [comment]
Yes, `touiteur.saumon.dev` for the frontend and `touiteur.saumon.dev/api` for the API. What do you think?
