### ISSUE TITLE
Set up an automated route documentation

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#8]
We need an automated route documentation
Swagger is probably the solution but propositon are welcome

**Comment by maximelouet** [comment]
Swagger seems to work only for REST APIs. I found this project to document GraphQL APIs: https://github.com/2fd/graphdoc

However it's important to note that a built-in explorer/debugger is included with GraphQL:
![image](https://user-images.githubusercontent.com/8074940/77524202-d8c5d580-6e7e-11ea-9299-3050dc0f9c72.png)

**Comment by AnastasiaPromtep** [comment]
This looks good.
I acknowledge the built-in explorer/debugger but i think we need a static way to access the route (Schema ?).

**Comment by maximelouet** [comment]
Yes so something like the tool I linked. I agree it's vital to have a static documentation of all the types/queries/mutations with associated comments for details.

**Comment by maximelouet** [comment]
https://github.com/2fd/graphdoc seems to be the best choice available. We'll have to generate the documentation as part of the CI/CD process, so I'll this issue open but it depends on https://github.com/lapoissonnerie/touiteur-api/issues/7

**Comment by maximelouet** [comment]
I just noticed there is a built-in documentation in the local GraphQL playground page:
![image](https://user-images.githubusercontent.com/8074940/78030053-6ad74d80-7359-11ea-8d21-a9e7daf6cc2e.png)

**Comment by AnastasiaPromtep** [comment]
This in-built doc could suffice.

**Comment by maximelouet** [comment]
Closing since the built-in documentation is sufficient.
