### ISSUE TITLE
Add a route documentation

### ISSUE THREAD

**Issue by AnastasiaPromtep** [lapoissonnerie/touiteur-api#9]
Every route of the API should be documented in one place **before** being implemented.
We should add a wiki-project page that documents all the route

**Comment by maximelouet** [comment]
Okay, but isn't this redundant with https://github.com/lapoissonnerie/touiteur-api/issues/8 ?
I believe an automatically generated documentation with proper comments is sufficient.

**Comment by AnastasiaPromtep** [comment]
It is !
